language: elixir
elixir:
  - 1.3
otp_release:
  - 18.3
  - 19.0

script:
  - MIX_ENV=dev mix do deps.get, dialyzer.plt
  - MIX_ENV=dev mix dialyzer --halt-exit-status
  - MIX_ENV=dev mix credo --strict
  - MIX_ENV=test mix do deps.get, test
